### ISSUE TITLE
Modifying mutable default datastructures in Python

### ISSUE THREAD

**Issue by brendongo** [returntocorp/semgrep-rules#211]
Detect when parameters in python function definitions are set to default dict or list and these are modified resulting in all instances of the default datastrucure being modifed.

Why:
- trophy case
- prove checks value if high frequency

# TODO
- Ways to overwrite/copy mutable list/dict:
    - [x] x = x or []
    - [x] x = x or {}
    - [x] x = copy.copy(x)
    - [x] x = copy.deepcopy(x)
    - [x] x = list.copy(x)
    - [x] x = dict.copy(x)
    - [x] x = x.copy()
    - [x] x = x[:]
    - [x] x = list(...)
    - [x] x = dict(...)
    - [x] x = [blah for blah in x]
    - [x] x = {blah for blah in x}
- Mutated list but it's fine
    - [ ] x.append(literal) on non conditional code path
    - [ ] x[literal] = literal on non conditional code path
    - [ ] Lots of instances when variable is called "cache" they are actually using it as a cache

**Comment by brendongo** [comment]
https://sgrep.live/gN5

Latest sgrep with statement hoisting/flattening does not solve any todoruleid's.

**Comment by brendongo** [comment]
https://sgrep.live/4L9

Looks like flattening is not great in this case since we want to fire on cases when the default datastructure is not copied.
